#!/bin/bash

# These commands take this form
# ./ops [script] [filename] [option]

script=${1}
filename=${2:-dev}
option=${3}

docker_compose_path="./docker"
droplet_name="freqtrade"

if [ -z $script ] ; then
  echo "please enter a command after ./ops"

elif [ $script == "provision" ] ; then
  ./scripts/provision

elif [ $script == "start" ] ; then
  echo "starting $filename"
  docker-compose -f $docker_compose_path/$filename.yml up

elif [ $script == "start-daemon" ] ; then
  echo "starting $filename"
  docker-compose -f $docker_compose_path/$filename.yml up -d

elif [ $script == "stop" ] ; then
  echo "stopping $filename"
  docker-compose -f $docker_compose_path/$filename.yml down

elif [ $script == "deploy" ] ; then
  echo "deploying $filename"

  # make sure directory exists
  docker-machine ssh $droplet_name "mkdir -p ~/freqtrade"

  # stop container
  docker-machine ssh $droplet_name "cd ~/freqtrade && ./ops stop $filename"

  # copy local files to remote server
  docker-machine scp -rf freqtrade/* $droplet_name:~/freqtrade
  docker-machine scp -rf docker $droplet_name:~/freqtrade/docker
  docker-machine scp ops $droplet_name:~/freqtrade

  # pull latest image and run docker-compose
  docker-machine ssh $droplet_name "docker pull freqtradeorg/freqtrade:develop && docker tag freqtradeorg/freqtrade:develop freqtrade"
  docker-machine ssh $droplet_name "cd ~/freqtrade && ./ops start-daemon $filename"
  # Open docker machine ssh session?

fi