#!/bin/bash

# These commands take this form
# ./ops [script] [filename] [option]

script=${1}
filename=${2:-dryrun}
option=${3}

docker_compose_path="./docker"
read -p "Enter the Digital Ocean Droplet Name [freqtrade]: " droplet_name
droplet_name=${droplet_name:-freqtrade}
export droplet_name

if [ -z $script ] ; then
  echo "please enter a command after ./ops"

elif [ $script == "provision" ] ; then
  ./scripts/provision

elif [ $script == "remove-machine" ] ; then
  docker-machine rm -f $droplet_name # this will delete remote instance as well

elif [ $script == "generate-default-configs" ] ; then
  ./scripts/generate-default-configs

elif [ $script == "start" ] ; then
  echo "starting $filename"
  docker-compose -f $docker_compose_path/$filename.yml up

elif [ $script == "start-daemon" ] ; then
  echo "starting $filename"
  docker-compose -f $docker_compose_path/$filename.yml up -d

elif [ $script == "stop" ] ; then
  echo "stopping $filename"
  docker-compose -f $docker_compose_path/$filename.yml down

elif [ $script == "logs" ] ; then
  echo "logs $filename"
  docker-compose -f $docker_compose_path/$filename.yml logs

elif [ $script == "remote-logs" ] ; then
  echo "logs $filename"
  docker-machine ssh $droplet_name "cd freqtrade && ./ops logs"

elif [ $script == "deploy" ] ; then
  echo "deploying $filename"

  # make sure directory exists
  docker-machine ssh $droplet_name "mkdir -p ~/freqtrade"

  # copy local files to remote server
  docker-machine scp -r -d config/ $droplet_name:~/freqtrade/config/
  docker-machine scp -r -d docker/ $droplet_name:~/freqtrade/docker/
  docker-machine scp -d ops $droplet_name:~/freqtrade/

  # stop/start docker-compose
  docker-machine ssh $droplet_name "cd ~/freqtrade && ./ops stop $filename && ./ops start-daemon $filename"

elif [ $script == "restart" ] ; then
  # stop/start docker-compose
  docker-machine ssh $droplet_name "cd ~/freqtrade && ./ops stop $filename && ./ops start-daemon $filename"

fi