#!/bin/bash
set -e

echo "Paste your Digital Ocean Access Token, followed by [ENTER]:"
read digitalocean_access_token

# For more info check out:
# Dockers Machine Digital Ocean driver: https://docs.docker.com/machine/drivers/digital-ocean/#options
# Docker Swarm: https://docs.docker.com/engine/swarm/

# Create droplet
docker-machine create \
  --driver digitalocean \
  --digitalocean-access-token $digitalocean_access_token \
  --digitalocean-region sfo1 \
  --digitalocean-size 1gb \
  --digitalocean-image ubuntu-14-04-x64-do \
  $droplet_name

# Add local SSH key to remote authorized_keys (optional)
cat ~/.ssh/id_rsa.pub | (docker-machine ssh $droplet_name "cat >> ~/.ssh/authorized_keys")
docker-machine ssh $droplet_name "cat ~/.ssh/authorized_keys"

# Get IP
ip=$(docker-machine ip $droplet_name)

# Install docker-compose
docker-machine ssh $droplet_name 'sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
docker-machine ssh $droplet_name 'sudo chmod +x /usr/local/bin/docker-compose'

# Output
echo "Droplet name is $droplet_name and ssh command: ssh root@$ip"